// Auto-generated by tools/gen_db.py — do not edit by hand.
// Tiny PROGMEM fallback only. Full DB is data/squishmallows.csv on SD.
// Regenerate: python3 tools/gen_db.py
#pragma once

#include <Arduino.h>

struct SquishEntry {
  const char* name;
  const char* full_name;
  const char* animal;
  const char* squad;
  const char* size;
  const char* retail_price_usd;
  const char* bio;
};

static const size_t SQUISH_FALLBACK_COUNT = 50;

static const SquishEntry SQUISH_FALLBACK[SQUISH_FALLBACK_COUNT] PROGMEM = {
  {"Archie", "Archie the Axolotl", "Axolotl", "Aquatic Squad", "8", "12.99", "Pink axolotl with frilly external gills."},
  {"Austin", "Austin the Avocado", "Avocado", "Food Squad", "8", "12.99", "Green avocado ripe for cuddles."},
  {"Avery", "Avery the Duck", "Duck", "Bird Squad", "8", "12.99", "Classic mallard duck with green-head accents."},
  {"Avery", "Avery the Mallard Duck", "Mallard Duck", "Bird Squad", "8", "12.99", "Classic mallard duck with green-head accents."},
  {"Benny", "Benny the Bigfoot", "Bigfoot", "Woodland Squad", "12", "19.99", "Classic brown bear hug machine."},
  {"Cam", "Cam the Cat", "Cat", "Pet Squad", "8", "12.99", "Soft gray cat who loves cozy naps."},
  {"Connor", "Connor the Cow", "Cow", "Farm Squad", "12", "19.99", "Black-and-white cow; one of the most collected characters."},
  {"Fifi", "Fifi the Fire Chief Fox", "Fire Chief Fox", "Original Squad", "8", "12.99", "Clever orange fox with a soft white belly."},
  {"Fifi", "Fifi the Fox", "Fox", "Original Squad", "8", "12.99", "Clever orange fox with a soft white belly."},
  {"Gordon", "Gordon the Shark", "Shark", "Aquatic Squad", "16", "29.99", "Blue shark with a friendly grin; common in large sizes."},
  {"Hans", "Hans the Hedgehog", "Hedgehog", "Woodland Squad", "8", "12.99", "Spiky-looking but soft woodland hedgehog."},
  {"Holly", "Holly the Owl", "Owl", "Woodland Squad", "5", "7.99", "Tiny hedgehog packed with joy."},
  {"Kai", "Kai the Orca", "Orca", "Aquatic Squad", "12", "19.99", "Black-and-white orca of the seas."},
  {"Kai", "Kai the Orca Whale", "Orca Whale", "Aquatic Squad", "12", "19.99", "Black-and-white orca of the seas."},
  {"Malcolm", "Malcolm the Mushroom", "Mushroom", "Bird Squad", "12", "19.99", "Friendly mallard duck popular in larger sizes."},
  {"Nessie", "Nessie the Loch Ness Monster", "Loch Ness Monster", "Mythical Squad", "12", "19.99", "Legendary lake monster made soft and friendly."},
  {"Patty", "Patty the Cow", "Cow", "Farm Squad", "12", "19.99", "Strawberry-spotted cow; a collector favorite."},
  {"Piper", "Piper the Penguin", "Penguin", "Pet Squad", "8", "12.99", "Wrinkly pug with endless charm."},
  {"Sunny", "Sunny the Bee", "Bee", "Bug Squad", "5", "7.99", "Bright yellow bee full of buzz."},
  {"Wendy", "Wendy the Frog", "Frog", "Original Squad", "8", "12.99", "Cheerful green frog; an early fan-favorite Squishmallow."},
  {"Amina", "Amina the Squirrel", "Squirrel", "Farm Squad", "8", "12.99", "Fluffy alpaca with a soft smile."},
  {"Aubrey", "Aubrey the Avocado", "Avocado", "Food Squad", "8", "12.99", "Another avocado favorite from food squads."},
  {"Augusto", "Augusto the Triceratops", "Triceratops", "Dino Squad", "12", "19.99", "Three-horned dinosaur with a frill."},
  {"Aurora", "Aurora the Unicorn", "Unicorn", "Mythical Squad", "12", "19.99", "Sparkly unicorn named for the dawn."},
  {"Autumn", "Autumn the Black Cat", "Black Cat", "Woodland Squad", "8", "12.99", "Fox with warm autumn coloring."},
  {"Autumn", "Autumn the Cat", "Cat", "Woodland Squad", "8", "12.99", "Fox with warm autumn coloring."},
  {"Autumn", "Autumn the Fox", "Fox", "Woodland Squad", "8", "12.99", "Fox with warm autumn coloring."},
  {"Ava", "Ava the Avocado", "Avocado", "Food Squad", "5", "7.99", "Petite avocado snack-sized cuddle."},
  {"Ava", "Ava the Chick", "Chick", "Food Squad", "5", "7.99", "Petite avocado snack-sized cuddle."},
  {"Avana", "Avana the Axolotl", "Axolotl", "Aquatic Squad", "12", "19.99", "Soft axolotl often found in bigger sizes."},
  {"Axel", "Axel the Beetle", "Beetle", "Bug Squad", "5", "7.99", "Little beetle with shiny-shell energy."},
  {"Azi", "Azi the Leopard Shark", "Leopard Shark", "Aquatic Squad", "8", "12.99", "Shark character from aquatic releases."},
  {"Azi", "Azi the Shark", "Shark", "Aquatic Squad", "8", "12.99", "Shark character from aquatic releases."},
  {"Aziza", "Aziza the Stingray", "Stingray", "Aquatic Squad", "8", "12.99", "Soft stingray of the ocean floor."},
  {"Azizi", "Azizi the Dragon", "Dragon", "Mythical Squad", "8", "12.99", "Dragon character from mythical releases."},
  {"Babs", "Babs the Blue Jay", "Blue Jay", "Pet Squad", "12", "19.99", "Plump bunny known for soft ears."},
  {"Belana", "Belana the Cow", "Cow", "Mythical Squad", "12", "19.99", "Fuzzy Bigfoot known for woodland vibes."},
  {"Bernice", "Bernice the Boba Tea", "Boba Tea", "Farm Squad", "5", "7.99", "Fluffy yellow chick full of peeps."},
  {"Brody", "Brody the Dinosaur", "Dinosaur", "Mythical Squad", "16", "29.99", "Large Bigfoot buddy known for big hugs."},
  {"Bruna", "Bruna the Cauldron", "Cauldron", "Mythical Squad", "8", "12.99", "Smaller Bigfoot woodland friend."},
  {"Bubba", "Bubba the Cow", "Cow", "Safari Squad", "16", "29.99", "Lovable elephant often sold in jumbo sizes."},
  {"Calvin", "Calvin the Latte", "Latte", "Pet Squad", "8", "12.99", "Short-legged corgi full of energy."},
  {"Carlos", "Carlos the Crab", "Crab", "Aquatic Squad", "5", "7.99", "Cheerful crab with soft claws."},
  {"Clover", "Clover the Bull", "Bull", "Farm Squad", "8", "12.99", "Spotted cow who loves clover fields."},
  {"Colm", "Colm the Christmas Tree Octopus", "Christmas Tree Octopus", "Aquatic Squad", "8", "12.99", "Octopus buddy of the deep."},
  {"Colm", "Colm the Octopus", "Octopus", "Aquatic Squad", "8", "12.99", "Octopus buddy of the deep."},
  {"Colton", "Colton the Cat", "Cat", "Pet Squad", "8", "12.99", "Friendly cat from pet-themed drops."},
  {"Conrad", "Conrad the Corn", "Corn", "Food Squad", "8", "12.99", "Yellow ear of corn ready to snack-hug."},
  {"Contessa", "Contessa the Raccoon", "Raccoon", "Woodland Squad", "8", "12.99", "Elegant raccoon with woodland flair."},
  {"Conway", "Conway the Highland Cow", "Highland Cow", "Farm Squad", "12", "19.99", "Fluffy Highland cow with long bangs."},
};

